/*
 * gldc_stats.h - GLdc Performance Instrumentation Counters (Phase 0 expanded)
 *
 * Provides per-frame counters for the full rendering pipeline:
 *   - Draw call submission (Patch B original)
 *   - Near-plane clipping (Phase 0 new)
 *   - Strip submission (Phase 0 new, for Phase 2)
 *   - Patch E fast-path (Phase 0 new, for Phase 3)
 *
 * Usage in game code:
 *   extern void glKosResetStats(void);
 *   extern const GLdcStats* glKosGetStats(void);
 *   extern void glKosPrintStats(void);
 *
 *   // Each frame, after EndDrawing():
 *   glKosPrintStats();
 *   glKosResetStats();
 */

#ifndef GLDC_STATS_H
#define GLDC_STATS_H

#include <stdint.h>

/* Define GLDC_ENABLE_STATS to compile with instrumentation.
 * When not defined, all stat macros become no-ops for zero overhead. */

typedef struct {
    uint32_t frame_no;

    /* --- Patch B: Draw submission counters --- */
    uint32_t draw_arrays_calls;
    uint32_t draw_elements_calls;
    uint32_t submit_vertices_calls;
    uint32_t fast_path_hits;
    uint32_t fast_path_misses;
    uint32_t headers_emitted;
    uint32_t state_dirty_events;
    uint32_t vertices_transformed;
    uint32_t texture_binds;
    uint32_t immediate_begin_calls;
    uint32_t immediate_end_calls;
    uint32_t immediate_vertices;

    /* --- Phase 0: Near-plane clipping counters --- */
    uint32_t clip_triangles_tested;     /* Total triangles entering clipping */
    uint32_t clip_all_visible;          /* Triangles fully in front of near plane */
    uint32_t clip_none_visible;         /* Triangles fully behind near plane */
    uint32_t clip_partial;              /* Triangles partially clipped */
    uint32_t clip_edges_generated;      /* New vertices generated by _glClipEdge */

    /* --- Phase 0: Scene submission counters --- */
    uint32_t scene_list_submits;        /* SceneListSubmit() calls */
    uint32_t scene_vertices_in;         /* Total vertices entering SceneListSubmit */
    uint32_t scene_headers_seen;        /* Headers encountered during submission */

    /* --- Phase 0: Strip counters (for Phase 2) --- */
    uint32_t strip_count;               /* Number of triangle strips submitted */
    uint32_t strip_vertices_total;      /* Total vertices across all strips */

    /* --- Phase 0: Patch E counters (for Phase 3) --- */
    uint32_t patchE_hits;               /* Draws routed through Patch E fast lane */
    uint32_t patchE_fallbacks;          /* Draws that fell back to GLdc */

    /* --- Phase 0: Derived metrics (computed at print time) --- */
    /* avg_vertices_per_draw = vertices_transformed / max(submit_vertices_calls, 1) */
    /* avg_strip_length = strip_vertices_total / max(strip_count, 1) */
    /* clip_rate = clip_partial / max(clip_triangles_tested, 1) */
} GLdcStats;

#ifdef GLDC_ENABLE_STATS

extern GLdcStats g_gldc_stats;

#define GLDC_STAT_INC(field)         (g_gldc_stats.field++)
#define GLDC_STAT_ADD(field, n)      (g_gldc_stats.field += (n))

#else

#define GLDC_STAT_INC(field)         ((void)0)
#define GLDC_STAT_ADD(field, n)      ((void)0)

#endif /* GLDC_ENABLE_STATS */

#endif /* GLDC_STATS_H */
